version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: pwbapp-db
    restart: always
    environment:
      - MYSQL_DATABASE=pwbapp
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - pwbapp-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  pwbapp-data:
    driver: local
